# Generated by Django 5.2.7 on 2025-10-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='code',
            new_name='value',
        ),
    ]
