# Generated by Django 5.2.7 on 2025-10-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_code_barcode_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barcode',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
